### ISSUE TITLE
auto generate secure token

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/a-little-more-secure#1]
So we do have a security param in the url. But if somehow an attacker uses because it's easy to find out with the automatic redirect that we would be attackable again. So what if we auto generate values in wp schedules of which only the latest two are valid. And as soon as the third one ist generated the first one will be invalid.

Advantage: More secure

Disadvantage: Users will not be able to skip the redirect page by copying the secure paramter url.

What are your thoughts on this @mkernel ?

**Comment by EdwardBock** [comment]
Oh and is the nonce I already use the same thing? 🤔

**Comment by mkernel** [comment]
@EdwardBock let's see where this path leads before allowing it to grow into a complicated mess :)

Maybe we need some kind of regenerated token, but I doubt we will. The current solution should throw wordpress-hacking-bots out and direct attacks are another story.

**Comment by EdwardBock** [comment]
Perfekt!
